# Generated by Django 4.2.3 on 2023-07-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_desc', models.CharField(max_length=500)),
                ('blog_like', models.IntegerField()),
                ('create_by', models.EmailField(max_length=34)),
            ],
        ),
    ]
