# Generated by Django 4.2.3 on 2023-09-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createview_student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='createview_student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='createview_student',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
    ]
