# Generated by Django 4.2.3 on 2023-09-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_desc', models.CharField(max_length=500)),
                ('publish_date', models.DateTimeField()),
            ],
        ),
    ]
